### ISSUE TITLE
taglib-ruby project website is giving a 404

### ISSUE THREAD

**Issue by jeremyjs** [robinst/taglib-ruby#109]
https://robinst.github.com/taglib-ruby/

This is returning a 404 for me, probably the github pages configuration and deployment just needs fixed. Or the link in the github repository description may be old.

Edit:
Yes, I realized that http://robinst.github.io/taglib-ruby/ is working properly. So the description just needs updated to point to the .io url instead.

**Comment by robinst** [comment]
Oh thanks, fixed!
