### ISSUE TITLE
Automatically creating id3v2 tag wth flac files?

### ISSUE THREAD

**Issue by s0nspark** [robinst/taglib-ruby#113]
I would like to always use id3v2 tags with flac files and I noticed that the accessor method in taglib supports passing a boolean to automatically create this tag if it does not exist. 

I did not see it referenced in the taglib-ruby docs, though. Is this possible? If not, could support for it be added?

**Comment by robinst** [comment]
Hmm which method are you referencing?: https://taglib.org/api/classTagLib_1_1FLAC_1_1File.html

**Comment by s0nspark** [comment]
These:

[ID3v2::Tag](https://taglib.org/api/classTagLib_1_1ID3v2_1_1Tag.html) * 	ID3v2Tag(bool create=false)
 
[ID3v1::Tag](https://taglib.org/api/classTagLib_1_1ID3v1_1_1Tag.html) * 	ID3v1Tag(bool create=false)
 
[Ogg::XiphComment](https://taglib.org/api/classTagLib_1_1Ogg_1_1XiphComment.html) * 	xiphComment(bool create=false)

Note that the create param defaults to false? I'm hoping to be able to set this to true on access so that the tag is created if it does not already exist instead of returning null.

Thanks!

**Comment by robinst** [comment]
Ah found them now: https://taglib.org/api/classTagLib_1_1FLAC_1_1File.html#a48569df79341414f29c03d4d3f4191c5

Supplying `true` for those already works. I just created a PR to add some tests for that, see here: https://github.com/robinst/taglib-ruby/pull/114

**Comment by s0nspark** [comment]
Awesome - thanks much!
