### ISSUE TITLE
Deterministic `rake swig`

### ISSUE THREAD

**Issue by jacobvosmaer** [robinst/taglib-ruby#136]
When I run `rake swig` on my development machine it is easy to get unwanted changes in the `_wrap.cxx` files. It would be nice if `rake swig` was deterministic. It makes life easier for contributors, and we could also check in CI that the generated files checked into Git are "correct".

Some things we would have to fix:

- pin a version of taglib to run swig against. we could make a script that downloads a specific taglib tarball and unpacks it locally
- run `sed` after `swig` to fix the `@SWIG` [comments](https://github.com/robinst/taglib-ruby/blob/33066c18859045f333848c7900fd9e0009d3dd8f/ext/taglib_base/taglib_base_wrap.cxx#L2173) to use a fixed path (we can use `swig -swiglib` to find the string that needs to be replaced)
- check the swig version from within `rake swig`
- ... anything else ?

**Comment by robinst** [comment]
Sounds good!

* We already have some logic to download and use a specific version of taglib/swig in CI, can we move that out of there and into rake or a script? If not that's fine, maybe it's too different.
* Yes, looks like we need `sed`. I've opened an issue about this with swig a long time ago: swig/swig#202

**Comment by jacobvosmaer** [comment]
OK! I can work on this.

**Comment by robinst** [comment]
Nice! Can you base it on `main`? We can later merge it into the `taglib-2` branch (or rebase).
