### ISSUE TITLE
CI cache is not working

### ISSUE THREAD

**Issue by jacobvosmaer** [robinst/taglib-ruby#140]
See this [example build](https://github.com/robinst/taglib-ruby/actions/runs/8580857507/job/23517327532).

<img width="1050" alt="Screenshot 2024-04-08 at 17 08 59" src="https://github.com/robinst/taglib-ruby/assets/1336311/2a3d59e9-b786-4f08-aa93-776630dbd785">

Note how much time is spent in "Install SWIG" and "Install TagLib" even though those steps are supposed to be cached.

I think our cache-less build is fast enough and I suggest we remove the cache steps from CI config to unclutter it.

**Comment by robinst** [comment]
Looking at https://github.com/actions/cache/blob/v2/README.md#example-workflow, it seems like we're missing a line like this in the `Install SWIG` step:

```
if: steps.cache-swig.outputs.cache-hit != 'true'
```

Same for the `Install TagLib` step. Do you want to try that first, before removing them?
