### ISSUE TITLE
Issue with installing taglib on Heroku

### ISSUE THREAD

**Issue by menan** [robinst/taglib-ruby#28]
Hi, I have taglib successfully installed on my heroku server under `/app/vendor/taglib-1.8` folder and my $PATH variable looks like this `PATH: /app/vendor/taglib-1.8/bin:/app/vendor/taglib-1.8/lib:/usr/local/bin:/bin`

But every time I push the files to the server with the taglib-ruby gem I get the taglib not installed error by the bundler. How do I fix it? I've been spending about 1 week trying to figure this out. I even tried adding this to my heroku config `CONFIGURE_ARGS:  -with-opt-dir=/app/vendor/taglib-1.8/lib` and still had no luck :/

Thanks.

**Comment by moofmayeda** [comment]
I'm getting the same error, @mad-raz. Did you ever figure it out? For me, it's being triggered by `require 'taglib'` in a rake task. What's even weirder is that the error persists even after I remove the mrrad buildpack, so it may be the taglib-ruby gem.

**Comment by iDuuck** [comment]
Didn't want to get out such an old entry. But since I am using this library and needed a way to get this working on Heroku, here is my solution:

---

Instead of doing this:

```ruby
require 'taglib'
```

do this:

```ruby
require 'taglib' if File.basename($PROGRAM_NAME) != 'rake'
```

At some point, the taglib isn't installed for rake commands, hence why you need to exclude those.
