### ISSUE TITLE
"Called without a valid file" on specific files

### ISSUE THREAD

**Issue by kahliii** [robinst/taglib-ruby#33]
Hey,

I'm trying to retrieve artist and title tags from a couple of mp3 files that belong to the same album so they have the same codec, tag format, etc. However, 3 of these 10 files throw an error, claiming:
    TagLib: FileRef::tag() - Called without a valid file.
    TagLib: FileRef::audioProperties() - Called without a valid file.

When opening the files in nautilus, the tags look just the same as for those files which taglib-ruby can read and they are all playable in rhythmbox as well. The code I'm using is the following:

``` ruby
  def read_metatags
    TagLib::FileRef.open(self.local_path) do |fileref|
      unless fileref.null?
        logger.info "Reading tags"
        tag = fileref.tag
        self.title = tag.title
        self.artist = tag.artist

        properties = fileref.audio_properties
        self.length = properties.length
      end
    end
    self.save!
  end
```

I want to use the basic API as I only need the artist and title tag but want to have the possibility of throwing various formats at the program.

I know it's probably hard to reproduce the problem without the sample files but the ones I used are all license-protected so I don't think it would be okay if I shared them here.

**Comment by coderawal** [comment]
I'm too getting this error "NoMethodError Error private method `open' called for TagLib::MPEG:Module" when I run the code from console and in resque workers the same error occurs the file path  is correct, and the code is :
```ruby```
TagLib::MPEG.open(rename_file) do |fileref|
                    unless fileref.null?
                      cover_tag = file.id3v2_tag
                      cover_img = cover_tag.frame_list('APIC').first
                      unless cover_img.blank?
                        ext = cover_img.mime_type.rpartition('/')[2]
                        o = [('a'..'i'), ('A'..'Z')].map { |i| i.to_a }.flatten
                        rand_string = (1..18).map { o[rand(o.length)] }.join
                        cover_file_name = "#{cover_path}#{File.basename(rename_file).chomp('.mp3').gsub('1-----','')}-#{rand_string}.#{ext}"
                        File.open(cover_file_name, "wb") { |f| f.write cover_img.picture }
                      end
                    end
                  end
```

**Comment by jacobvosmaer** [comment]
@coderawal could you try `TagLib::MPEG::File.open` instead of `TagLib::MPEG.open`?

**Comment by coderawal** [comment]
thanks @jacobvosmaer now it's working.
