### ISSUE TITLE
Segfault when accessing picture with closed TagLib::FLAC::File

### ISSUE THREAD

**Issue by sdalu** [robinst/taglib-ruby#50]
The following code generally lead to a segfault

``` ruby
        cover = TagLib::FLAC::File.open(file) {|flac|
            flac.picture_list.reject {|p| 
                p.type != TagLib::FLAC::Picture::FrontCover 
            }.first 
        }
        puts cover.render
```

ruby 2, taglib 1.9.1, ruby-taglib 0.6.0

**Comment by robinst** [comment]
> For making this raise an exception instead of segfaulting, we should probably also unlink pictures inside free_taglib_flac_file (in ext/taglib_flac/taglib_flac.i).

This has since been done, closing this.
