### ISSUE TITLE
CHAP and CTOC support

### ISSUE THREAD

**Issue by attilagyorffy** [robinst/taglib-ruby#63]
Hi,

Taglib has added [CHAP and CTOC support](https://github.com/taglib/taglib/pull/173) back in July. It is not in a stable release yet, but I'd be interested in knowing what would it take to add bindings in taglib-ruby. I am not a C++ developer but I'd love to know if this was a lot of effort and if I could help. I don't quite know how one would add native extension support to begin with. Any help would be greatly appreciated.

Thanks,

-- Attila

**Comment by montekaka** [comment]
Do we have any method to add the chapter info?
thanks

**Comment by robinst** [comment]
@montekaka No, not yet. As for upgrading to a newer minimum version of TagLib, we could upgrade to 1.9.1 (that's in [Debian stable](https://packages.debian.org/jessie/libtag1-vanilla) now). But CHAP/CTOC were only released in 1.10.

**Comment by miyagawa** [comment]
Hi, looks like version 1.0.0 of this gem has bumped the TagLib requirement to 1.11, meaning adding CHAP/CTOC isn't a problem wrt its dependency, I suppose.

I would love to be able to tag chapters in my Ruby workflow for podcasts -- currently I'm shelling out to Python3 to use Mutagen.

**Comment by neilberkman** [comment]
Demo of an MP3 tagged using  @iamAzeem's  code in  #103 in Overcast. This uses:

* TableOfContentsFrame
* for each chapter:
  * TextIdentificationFrame for title (TIT2)
  * UserUrlLinkFrame (WXXX) for an external URL for each chapter
  * AttachedPictureFrame for a chapter image
![chap_demo](https://user-images.githubusercontent.com/37657/104052428-93209200-519e-11eb-9366-3b0ae888d76c.gif)

**Comment by iamAzeem** [comment]
@neilberkman:
Thank you for such an elaborate example! That [repo](https://github.com/neilberkman/chapter-demo) is really helpful!

**Comment by robinst** [comment]
Thanks @iamAzeem, released in 1.1.0 :tada:: https://github.com/robinst/taglib-ruby/blob/main/CHANGELOG.md#110---2021-01-20

**Comment by razum2um** [comment]
Just in case anybody interested in alternatives, see https://github.com/hardcodefm/ruby-mp3info or [PR](https://github.com/moumar/ruby-mp3info/pull/72)

Also, [test example](https://github.com/moumar/ruby-mp3info/pull/72/commits/7a8b777cd54c9c29a71cd0d4be224f3aafc860d3), [real-world example](https://github.com/hardcodefm/hardcode/blob/23f9f211909124bfeef0f02e8f03870cf88e1f58/bin/thor#L58)
