### ISSUE TITLE
Updating Lyrics

### ISSUE THREAD

**Issue by omerkhan** [robinst/taglib-ruby#64]
I'm trying to replace ID3 Editor with taglib-ruby. I've been able to update all the required ID3 tags except for (a) lyrics and (b) podcast description. In ID3 Editor these two are described as:
1) -ls utext            Set the lyrics or text transcription
2) -pcds  utext      Set the podcast description
I can't seem to figure out how to update these two tags using taglib-ruby. Any help would be appreciated or if you could just point me to some sample code specifically for these two tags.
Thanks.

**Comment by robinst** [comment]
Also, to see what frames ID3 Editor wrote, do something like this:

```
TagLib::MPEG::File.open(path, false) do |file|
  tag = file.id3v2_tag
  tag.frame_list.each do |frame|
    puts frame.frame_id
  end
end
```

**Comment by robinst** [comment]
Closing this, let us know if you run into a bug or need further help.

**Comment by omerkhan** [comment]
Thanks Robin -- that's very helpful.
