### ISSUE TITLE
comment tag not being written

### ISSUE THREAD

**Issue by coderawal** [robinst/taglib-ruby#65]
I'm wondering why comment metadata not being written for mp3 files my code looks like below but all other tag get written except comment :-
```ruby
def update_music_metadata?(song)
    TagLib::FileRef.open(song.attachment_url) do |fileref|
      unless fileref.null?
        tag = fileref.tag
        tag.title = song.title
        tag.artist = song.artist
        tag.album = song.album
        tag.year = song.year.to_i
        tag.track = song.track.to_i
        tag.genre = song.genre
        tag.comment = song.comment
        if fileref.save
          return true
        else
          return false
        end
      end
    end
  end
```

**Comment by robinst** [comment]
What version of taglib (the C++ library) and taglib-ruby are you using? What is printed when you run the following on one of the files?:

```ruby
TagLib::MPEG::File.open(path) do |file|
  file.id3v2_tag.frame_list.each do |frame|
    p [frame.frame_id, frame.to_s]
  end
end
```

Also, where is it that you don't see the comment frame? When reading it with taglib-ruby, or in another program?

**Comment by coderawal** [comment]
I'm using taglib-ruby version 0.7.0, and the o/p for above code snippet is as: 
["COMM", "00001F94 00001ED1 00013A16 00011006 0000E978 0000E978 000091A7 00009192 0001DFCB 0001F053"]
["COMM", "00000000 00000210 00000A3E 0000000000C4D3B2 00000000 00B271A2 00000000 00000000 00000000 00000000 00000000 00000000"]
["TPE1", "Tove Lo"]
["TALB", "Free Download"]
["TPE2", "The Chainsmokers"]
["TIT2", "Habits (The Chainsmokers Remix)"]
["TCOP", "The Chainsmokers"]
["TPUB", "The Chainsmokers"]
["TDRC", "2014"]
["TDRC", "2014"]
["COMM", "Release Day: 7 January"]
["TRCK", "01/01"]
["TCON", "Big Room"]
["TBPM", "128"]
["WXXX", "[] vk.com/personalmusiccollection by Complextor"]
["APIC", "[image/jpeg]"]

**Comment by robinst** [comment]
So it looks like there are 3 comment frames in the tag (the `COMM` ones). Doing `tag.comment = comment` adds a new comment, but doesn't clear the existing ones. To remove all before adding a new one, you can do `tag.comment = nil`.

Does that resolve the problem for you?

**Comment by coderawal** [comment]
Thanks robinst, finally i understood and solved it your way.

**Comment by robinst** [comment]
Good to hear, thanks for confirming.
