### ISSUE TITLE
Set metadata in ogg files

### ISSUE THREAD

**Issue by Franx0** [robinst/taglib-ruby#66]
Hi everyone,
I'm newbie in TagLib but I'm discover so many new interesting things.
I'm working with Rails but I'm having problems with .ogg files. 
It's my code:

``` ruby
def set_audio_tags
  TagLib::Ogg::Vorbis::File.open(self.audio.path, read_properties = true) do |file|
    tag = file.tag
    tag.title = 'file.title'
    tag.artist = 'abcd'
  end
end
```

and it's my trace of file:

``` ruby
 #<TagLib::Ogg::Vorbis::File:0x0000000a5d8180 @__swigtype__="_p_TagLib__Vorbis__File">
```

but I can't set 'tag' because it's nil

Can anyone explain me how to create new audio metadata fields in OGG::Vorbis fields?

Thanks for all ;)

**Comment by robinst** [comment]
Works fine here, just tried it using the first file from here: http://www.vorbis.com/music/

`tag` is `nil`, are you sure? Have you tried adding a `file.save` as the last line of the block? Otherwise the fields are not saved to the file.

**Comment by Franx0** [comment]
hi @robinst thnaks for your answer. I sad to say that your answer doens't solve the problem.

```ruby
def set_audio_tags
  TagLib::Ogg::Vorbis::File.open(self.audio.path, read_properties = true) do |file|
    #I write a binding.pry here and it say that file.tag = nil so if I try to write file.tag.title = 'somethig' it say
     that 'NoMethodError - undefined method `title=' for nil:NilClass:'

    tag = file.tag
    tag.title = 'file.title'
    tag.artist = 'abcd'
  end
end
```

**Comment by robinst** [comment]
What's `self.audio.path`? It has to be an absolute file system path.

**Comment by Franx0** [comment]
@robinst self.audio.path is  the absolute path of my audio file. I can't figure out what's wrong with it.

**Comment by robinst** [comment]
Hmm.. Is it possible for you to upload the audio file somewhere and send me the link?
