### ISSUE TITLE
 APIC Upload with Paperclip

### ISSUE THREAD

**Issue by dejesus-git** [robinst/taglib-ruby#69]
Like a previous issue, I am trying to read and extract a picture frame and prepare it to be uploaded using paperclip. I have read the documentation and even tried what was recommended in this issue, https://github.com/robinst/taglib-ruby/issues/29 , but I can't figure out how I should set it up for paperclip.

**Comment by robinst** [comment]
I'll need to see the code you're using to help. It would be best if you could provide a standalone script that shows the problem without paperclip.

**Comment by dejesus-git** [comment]
In my tracks model I have
```
require 'taglib'

before_save :extract_coverart

def extract_coverart
	TagLib::MPEG::File.open(audio.queued_for_write[:original].path) do |file|
	   tag = file.id3v2_tag
	   covers = tag.frame_list('APIC')
          unless covers.empty?
	     cover = covers.first
           File.open(audio.queued_for_write[:original].path, "w+") do |f|
              self.coverart  = f.write(cover.picture)
	       end
          end
        end
	end
```
I continue receiving the "\xFF" from ASCII-8BIT to UTF-8 error.  I have tried other code where I do manage to save to a binary column and the file looks like \xFF\X.... but I'm not sure how I'm supposed to convert that into something paperclip can use.

**Comment by robinst** [comment]
As already mentioned, a standalone script and a example audio file would be useful.

Are you using Windows? Try changing `"w+"` to `"wb+"`.
