### ISSUE TITLE
Heroku Installation

### ISSUE THREAD

**Issue by franksama** [robinst/taglib-ruby#70]
Hi,

I'm getting an error on heroku when trying to install taglib-ruby.

I have taglib installed at `/app/vendor/taglib` but not sure how to set Heroku bundle configs to do the --with-opt-dir

Any help would be appreciated

Thanks!

**Comment by robinst** [comment]
Try setting the `CONFIGURE_ARGS` environment variable to `--with-opt-dir=/app/vendor/taglib`. It would also be good to have a look at the log files, they might include a clue as to what's going wrong.

Other than that, I'm afraid I can't really help with Heroku much.
