### ISSUE TITLE
Is there a way to compact an ID3v2 tag or remove it entirely from an MP3 file?

### ISSUE THREAD

**Issue by floehopper** [robinst/taglib-ruby#71]
As far as I can tell, if an MP3 file has a large image in an APIC frame, but that is later replaced by a smaller image, the spare bytes are not recovered i.e. while the individual frame size is smaller, the overall tag size (available via the header) is the same size as it was originally.

While the result is perfectly valid from an MP3 & ID3v2 point of view, I've been running into [an obscure Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=582898) which seems to be related to the overall tag size being quite large.

Is there a way to compact the tag so it has no padding bytes (i.e. the tag size is just the total of the sum of the frame sizes)?

Alternatively, is there a way to completely remove a tag from an MP3 file (i.e. not just remove all the frames)?

**Comment by floehopper** [comment]
Please ignore my earlier question. I've realised I can do what I want by calling `TagLib::MPEG::File#strip` with the default argument and then re-creating the ID3v2 tag using `TagLib::MPEG::File#id3v2_tag(true)`. Closing.

**Comment by jacobvosmaer** [comment]
Great! I started looking and I couldn't find this myself. Hadn't reached the MPEG::File class yet in the docs. Glad to see it's possible.
