### ISSUE TITLE
Windows Installation, Can't Find Taglib

### ISSUE THREAD

**Issue by benrr101** [robinst/taglib-ruby#72]
I really hate to ask a question via github, but I'm at the end of my rope for this. I've gone through the difficulties of building taglib and getting it installed on my machine. My next step is to install the taglib-ruby gem, but I haven't been able to do it. As far as I can tell, it comes down to the native extension build not being able to find taglib. Should I be setting an environment variable differently?

Here's the command I'm running and the output:
```
> set CONFIGURE_ARGS="--with-tag-dir='D:/Program Files (x86)/taglib'"
> gem install taglib-ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing taglib-ruby:
        ERROR: Failed to build gem native extension.

    current directory: E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taglib-ruby-0.7.1/ext/taglib_base
E:/Programs/Ruby23-x64/bin/ruby.exe -r ./siteconf20161026-7416-s2tdpw.rb extconf.rb
checking for main() in -lstdc++... yes
checking for main() in -ltag... no
You must have taglib installed in order to use taglib-ruby.

Debian/Ubuntu: sudo apt-get install libtag1-dev
Fedora/RHEL: sudo yum install taglib-devel
Brew: brew install taglib
MacPorts: sudo port install taglib

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=E:/Programs/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-tag-dir
        --with-tag-include
        --without-tag-include=${tag-dir}/include
        --with-tag-lib
        --without-tag-lib=${tag-dir}/lib
        --with-stdc++lib
        --without-stdc++lib
        --with-taglib
        --without-taglib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/taglib-ruby-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taglib-ruby-0.7.1 for inspection.
Results logged to E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/taglib-ruby-0.7.1/gem_make.out
```

FWIW, the docs for installing do not include anything about setting up taglib on windows, anymore. The website (as opposed to the github readme) mentions that this isn't an issue on windows because taglib is included with the binary package. However, it's not obvious from the docs how to install the binary gem or if the binary package even exists anymore.

**Comment by robinst** [comment]
Hey, don't worry about asking here :).

So yeah, we haven't released a binary gem recently because it's so painful to have the whole cross-compilation working (and keep it working). And I'm not using Windows myself.

From the output it looks like it didn't pick up the CONFIGURE_ARGS hey? Maybe it's because there is a space in the path? Have you tried moving the taglib files to a different path that doesn't include spaces?

**Comment by benrr101** [comment]
Thanks for the suggestion! That actually worked, but not for the reason I expected. It looks like there's an issue with parsing quotes in the CONFIGURE_ARGS. Omitting the quotes worked perfect, but moving the files to another folder without spaces was a prereq to getting that to work.

Since the docs and notes during installation failures don't really say anything about installing TagLib and the gem on Windows, would it be ok if I submitted a pull request with some small updates to include basic instructions for Windows users?

**Comment by robinst** [comment]
A pull request for extending the documentation would be more than ok :)!
