### ISSUE TITLE
Windows usage, specified module could not be found taglib_base.so

### ISSUE THREAD

**Issue by benrr101** [robinst/taglib-ruby#73]
Now that I've got the gem installed, I'm unable to do `require 'taglib'`. I'm getting this error:

```
LoadError: 126: The specified module could not be found.   - E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taglib-ruby-0.7.1/lib/taglib_base.so
```

Which from what I can tell from similar issues with sqlite2 and other gems, this is because the taglib binaries aren't in the path environment variable. However, my path variable does include `E:\Programs\taglib-1.9.1\bin`. And just to rule out the obvious, taglib_base.so does exist at the path in the error message. Any chance I'm missing something obvious? (note, taglib was compiled with MinGW, but I'm running ruby from the standard cmd prompt. I noticed a bit on expanding the path variable in taglib.rb on mingw32, which I thought might be related)

**Comment by robinst** [comment]
Yeah, the path expansion is supposed to take care of this. Can you print ENV['PATH'] after those lines in taglib.rb and see which directories it contains?

**Comment by benrr101** [comment]
Sorry for the delay. Here's what I have for my path variable after the expansion in taglib.rb (can confirm it's running in MinGW32). I cleaned it up to make it easier to read, too.

```
E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/bin;
E:\Programs\ConEmu\ConEmu\Scripts;
E:\Programs\ConEmu;
E:\Programs\ConEmu\ConEmu;
E:\Programs\GTK\bin;
C:\ProgramData\Oracle\Java\javapath;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Skype\Phone\;
C:\Users\[redacted]\.dnx\bin;
C:\Program Files\Microsoft DNX\Dnvm\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
E:\Programs\Git\cmd;
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\M;
E:\Programs\Node.js\;
E:\Programs\Ruby23-x64\bin;
C:\Users\[redacted]\AppData\Local\atom\bin;
C:\Users\[redacted]\AppData\Local\Microsoft\WindowsApps;
C:\Users\[redacted]\AppData\Roaming\npm;
E:\Programs\CMake\bin;
E:\Programs\MingW64\bin;
E:\Programs\taglib-1.9.1\bin;
E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taglib-ruby-0.7.1/lib

LoadError: 126: The specified module could not be found.   - E:/Programs/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taglib-ruby-0.7.1/lib/taglib_base.so
```

My initial thought is that it'd be messed up because the directory separator used in the path that's added isn't the standard one for Windows. But considering that Ruby can usually work with either kind of path separator, I'm not sure that that's a problem.

**Comment by robinst** [comment]
Please see #62.
