### ISSUE TITLE
Support for Taglib 1.11.1

### ISSUE THREAD

**Issue by Sigill** [robinst/taglib-ruby#78]
Hi everyone,

Taglib 1.11.1 starts being quite mainstream: Debian stable, Ubuntu 17.10, Fedora 25/26/27, the next Mint...

Unfortunately, Taglib 1.11 introduced a new way to handle pictures in Ogg files. They were previously accessed as standard tags (base64-encoded), but are now available as a list of FLAC::Picture objects. Which means that on those modern distributions, Taglib-ruby (which is based on Taglib 1.7 if I'm correct) can't access pictures from Ogg files anymore.

Since a tool of mine requires this feature, I'm willing to try to upgrade Taglib-ruby for a Taglib 1.11.1 support. I've never used Swig or native gems before, just played a bit on the last few weeks, but it seems doable and fun.

Any thought/advice/suggestion?

**Comment by robinst** [comment]
Yeah, I think it makes sense to raise our minimum TagLib version to 1.11 nowadays.

I'm unlikely to work at this in the near future, but I'm willing to help/mentor anyone contributing this.

**Comment by braindeaf** [comment]
Is it likely that you (@Sigill) will take on the project? We're investigating corrupt flac(s) after tagging and we can't upgrade Taglib to see if this resolves it.

**Comment by Sigill** [comment]
@braindeaf That is not my goal, I'm just fixing a few things that broke my app.
But feel free to open a new Issue, if I stumble accross something while working on the support for Taglib 1.11, I'll do my best to help you!

**Comment by robinst** [comment]
Reopening, haven't released this yet.

**Comment by robinst** [comment]
Release with 1.0.0 now! :tada:
