### ISSUE TITLE
Push latest version to rubygems

### ISSUE THREAD

**Issue by DomenicF** [robinst/taglib-ruby#88]
Hello,

Could the latest gem be published to rubygems.org? I made a pull request because I was having issues getting the latest version to build locally with the latest version of bundler/Ruby but thinking about it it probably isn't necessary to do this (https://github.com/robinst/taglib-ruby/pull/87). Was just hoping to get the latest features of taglib on Ruby Gems.

Thanks!

**Comment by robinst** [comment]
Done, released 1.0.0! :tada:
