### ISSUE TITLE
TestID3v2Memory fails on my build

### ISSUE THREAD

**Issue by jameswyper** [robinst/taglib-ruby#92]
I'm having a go at fixing issue #91 - this is my first time working with Ruby extensions so bear with me please.  I'm running inside a VM with Ubuntu 19.04.  This includes swig 3.0.12 - I know the instructions call for 3.0.7 but not sure if that's a minimum or not.  So far I haven't touched the code, just forked and cloned it and followed the build instructions given (adapting for Ubuntu). I'm just trying to compile a known good version.

`rake swig ` generates a couple of warnings:

```
cd ext/taglib_aiff && /usr/bin/swig -c++ -ruby -autorename -initname taglib_aiff -I/usr/local/include -I/usr/include taglib_aiff.i
/usr/include/taglib/aifffile.h:57: Warning 401: Nothing known about base class ' TagLib::RIFF::File'. Ignored.
cd ext/taglib_wav && /usr/bin/swig -c++ -ruby -autorename -initname taglib_wav -I/usr/local/include -I/usr/include taglib_wav.i
/usr/include/taglib/wavfile.h:58: Warning 401: Nothing known about base class 'TagLib::RIFF::File'. Ignored.
```
`rake clean compile` appears to work but then `rake test` core dumps.

`rake test TESTOPTS="-v"` reports

```
TestID3v2Memory:
  test: TagLib::ID3v2 should not corrupt memory with ByteVector. :   Aborted (core dumped)
rake aborted!
```

Before I spend more time digging into this (bearing in mind it's all new to me), does anyone have any ideas where I should look?  Thanks.

**Comment by jameswyper** [comment]
I'm going to try and test on a Fedora VM just in case this and issue 91 are something specific to Ubuntu (I'm using their taglib).

**Comment by Sigill** [comment]
Swig 3.0.7 is currently required due to an issue in releases 3.0.8 to 3.0.12.
See https://github.com/robinst/taglib-ruby/issues/86#issuecomment-570939013.

**Comment by jameswyper** [comment]
Thank you so much for that!  I've removed the Ubuntu swig package, built and installed 3.0.7 from source and rake test is now running cleanly.
