### ISSUE TITLE
TagLib::FileRef.open doesn't seem to work for Tempfile

### ISSUE THREAD

**Issue by mlodato517** [robinst/taglib-ruby#97]
I'm seeing `TagLib::RileRef` operate differently when I use `Tempfile` instead of a permanent file.

I originally had this code in a controller:
```rb
    Tempfile.create("temp.wav", binmode: true) do |temp|
      temp.write(request.body.read)
      temp.rewind

      TagLib::FileRef.open(temp.path) do |file|
        puts "file is null? #{file.null?}"
      end
    end
```
and `file.null?` was always `true`. I changed the code to:
```rb
    IO.binwrite("temp.wav", request.body.read)

    TagLib::FileRef.open("temp.wav") do |file|
      puts "file is null? #{file.null?}"
    end
```
and `file.null?` was finally `false`.

Is this expected? Or am I setting up the `Tempfile` incorrectly?

**Comment by jacobvosmaer** [comment]
1. You don't need `temp.rewind` because `TagLib::FileRef.open(temp.path)` will reopen the file, starting at position 0.
2. Before `temp.write`, try adding `temp.binmode`. I wonder if the reason your second example succeeds is because it uses `IO.binwrite`.

**Comment by mlodato517** [comment]
> You don't need `temp.rewind` because `TagLib::FileRef.open(temp.path)` will reopen the file, starting at position 0.

Awesome! Good to know 👍 

> Before `temp.write`, try adding `temp.binmode`.

Interesting. I had `binmode: true` in the `Tempfile.create` but I will try that!

**Comment by jacobvosmaer** [comment]
OK so I overlooked the `binmode` on Tempfile.create.

Still, I would check the file contents. Perhaps add `system('md5', temp.path)` in the first example and `system('md5', 'temp.wav')` in the second.

Another thought: could it be that FileRef uses the file extension as a hint?

**Comment by mlodato517** [comment]
> could it be that FileRef uses the file extension as a hint?

I definitely think this is true. If I change the file to `temp.foo` in the `IO.binwrite` example, it doesn't work either. But I thought the `.wav` in the `Tempfile` would keep the extension the same. I just assumed `Tempfile` put it in a temporary place but didn't tack anything on to the filename. I'll investigate!

**Comment by jacobvosmaer** [comment]
`puts temp.path` might shed light on what the actual tempfile name is.

**Comment by jacobvosmaer** [comment]
I think you want `Tempfile.create(['temp', '.wav'], binmode: true)`.

**Comment by mlodato517** [comment]
Yep that did it! Thank you!
